### ISSUE TITLE
什么时候开源 Windows XP ！

### ISSUE THREAD

**Issue by dylanbai8** [Microsoft/MS-DOS#10]
:）

**Comment by Anduin2017** [comment]
登录只为点赞

**Comment by CecilHarvey** [comment]
Translate: When Windows XP will be open sourced :)

**Comment by Formyown** [comment]
看样子也是30年之后了

**Comment by darouwan** [comment]
Actually few people would read the source code as the source code of Windows XP is a giant engineering

**Comment by dylanbai8** [comment]
收购 Github 却只开源 MS-DOS 并不够诚意！

**Comment by dylanbai8** [comment]
：）

**Comment by zhangjun1996** [comment]
开源了也没用，源码太多，还是搞linux是正道，其他的通通是邪教😄

**Comment by chilauhe** [comment]
hey guys, there's no chance. wake up, don't  drown in your Chin*** Dream. If M$ do it, the so called PROs of some great country will copy it then name it a completely IPR OS.😂😂😂

**Comment by mikhailnov** [comment]
@darouwan Wine developers will definitely read it.

**Comment by bitcrazed** [comment]
Sorry, no plans.

**Comment by hifocus** [comment]
The first issue that been closed [QwQ]

**Comment by zanjie1999** [comment]
強勢圍觀
什麼時後開源Windows 10

**Comment by NimaQu** [comment]
lol

**Comment by stevenliuit** [comment]
six six six

**Comment by laosb** [comment]
请不要使用 Issues 进行版聊。
Please do not use Issues Tracker to chat.

**Comment by kalluwa** [comment]
@Formyown 所以一定要活到这么久啊，千万不要猝死。

大家都注意保重身体

**Comment by qzfyn** [comment]
什么时候NTFS开源

When NTFS will be Open source😷

**Comment by ironfeet** [comment]
有生之年

**Comment by FrankHB** [comment]
> 
> 
> it would be after win3.x win95 win98 winMe win2000 , ummmmm

It seems that some of them have been already leaked.

**Comment by lizhaode** [comment]
没人想开源 VS 吗？
Does anyone want to open source Visual Studio?

**Comment by wotmshuaisi** [comment]
no freaking way

**Comment by adolli** [comment]
-.-

**Comment by Yurunsoft** [comment]
开源也看不懂，然并卵
Open source can't understand, but eggs

**Comment by mumu3w** [comment]
特地登录只为给楼主顶一贴。
