### ISSUE TITLE
Some source .pas files placed to bin dir instead sources

### ISSUE THREAD

**Issue by VladimirMangos** [Microsoft/MS-DOS#13]
I see some pascal source .pas files in BIN dir. May be its must be in source dir?

**Comment by bitcrazed** [comment]
No, these are the source code for utilities that OEM's used to, for example, [parse filenames](https://github.com/Microsoft/MS-DOS/blob/master/v2.0/bin/FILBP.PAS), and [draw histograms of profiling data](https://github.com/Microsoft/MS-DOS/blob/master/v2.0/bin/PROHST.PAS), helping OEM's ensure that MS-DOS ran as expected on their hardware.
