### ISSUE TITLE
Can it run Crysis?

### ISSUE THREAD

**Issue by aTmG** [Microsoft/MS-DOS#15]
I am curious. I also want to know if it can run Minecraft and GTA V

**Comment by mudlord** [comment]
Go away.

**Comment by AndresReyesTech** [comment]
Sorry guys, certainly this is off topic, but look the source code is just porn to me (and even better)...

**Comment by lulujyc** [comment]
lolololol u serious?

**Comment by maakinoh** [comment]
Try it and see what happens

**Comment by NatoBoram** [comment]
You'd need graphics drivers for GTA V and a Java version that runs on MS-DOS for Minecraft. I'm not versed in the requirements for Crysis, however.

**Comment by Ryukote** [comment]
Try to port [Jesus.JS](https://github.com/edankwan/Jesus.js?files=1) to MS-DOS and you would be able to run any game you want.

**Comment by bitcrazed** [comment]
Alas, no. Crysis requires more than 640KB to run ;)

**Comment by rodrigouchoatw** [comment]
If you install MemMaker and unload your mouse from autoexec.bat, you're good to go.
