### ISSUE TITLE
Would you please release Windows 3.* source code?

### ISSUE THREAD

**Issue by netroby** [Microsoft/MS-DOS#16]
I read the msdos source code. it's awesome, 
would you please release windows 3.* source code?
It does not sale in today.

**Comment by netroby** [comment]
Windows 9x may be a bit hard to opensource, but windows 3.* seems will not harmful

**Comment by dhrdlicka** [comment]
32-bit versions of Windows still ship with the "Windows on Windows" subsystem (although disabled by default nowadays), which is based on Windows 3.1. I can see that being an obstacle in releasing its source code.

**Comment by FateForWindows** [comment]
inb4 "sorry, no plans"
Seriously Microsoft, make this happen.

**Comment by bitcrazed** [comment]
Sorry, no plans ;)

**Comment by FateForWindows** [comment]
dammit
![image](https://user-images.githubusercontent.com/14127573/46322075-e580aa80-c5b4-11e8-84ba-da3e83933a12.png)

**Comment by neilmacneil123** [comment]
Do it bi! I throw in a half a deck of smokes.  Tailor mades!
