### ISSUE TITLE
Please upload MSDOS 5.0 source code as well

### ISSUE THREAD

**Issue by iddq** [Microsoft/MS-DOS#174]

**Comment by iddq** [comment]
Do you have any idea what can be the reason of it?

**Comment by lnaie** [comment]
> Do you have any idea what can be the reason of it?

still in use? :D

**Comment by xargsyan** [comment]
@SuperOP535 when they said it?

**Comment by ExE-Boss** [comment]
@xargsyan In&nbsp;https://github.com/Microsoft/MS-DOS/issues/53#issuecomment-427159848.

**Comment by bitcrazed** [comment]
Sorry - no plans to open newer versions of MS-DOS at this time.

**Comment by denzuko** [comment]
@iddq anything pass 3.0 has code contributed from novell and at&t such as memory management, networking, file locking, and semi-functional POSIX support. 3.0 was a major rewrite of the kernel that honestly a lot suspect are from cloning DR-DOS.
