### ISSUE TITLE
MS-DOS 6.22 Open Source Code

### ISSUE THREAD

**Issue by xargsyan** [Microsoft/MS-DOS#201]
Lets directly ask for MS-DOS 6.22 - the last pure MS-DOS!

**GitHubians** - Lets up-vote, for the people mentioned in the next line
**Microsoftians** || @bitcrazed - Please raise this question to your management - to be more open-source and bring (lots and lots of) fun to your old-school users :) 

---
Why?
It had lots of good tools and games compared to previous versions that fans and old-school users enjoy.
Would be fun for MS-DOS-ers to modify, run old tools, play games, experiment on the latest pure MS-DOS :)

11100 stars are already given for this GitHub project! And counting... (and last 3 stars were added while I was typing this).
That means 100K+ people would star it if they _knew_ about it.
That means 1M+ would star if they _see_ MS-DOS 6.XX codes.
(That perhaps means 10M+ would have fun with it)

And why not?
It is not supported and (hopefully) is not used anywhere anymore, so should have no security/copyright/reusing/concurrent product development risks. 

---

We are waiting for MS-response (or a MS-surprise)...

Thanks

**Comment by mdtauk** [comment]
The release of the early MS-DOS versions, and their age may be linked.  And when you move towards the 6.X era, you border on Windows source code issues, which may prevent Microsoft from releasing the source.

I'm not saying don't ask for it, but just be understanding if Microsoft do not agree with the ask.

**Comment by dl200010** [comment]
I though that with the release of XP (NT line of Windows) the old 9x code, thus the MS-DOS code, was dropped. Not saying this is what happened, only Microsoft will know that. Just thought I would drop my 2 cents in the bucket, too.

**Comment by mobluse** [comment]
As a fall back, I think the source code of MS-DOS 3.2 would be interesting because that was my first MS-DOS that came with [Amstrad PC1512](https://en.wikipedia.org/wiki/PC1512) and it supports 720KB diskettes. MS-DOS 3.3 would also be interesting since it supports 1.44MB diskettes.

**Comment by sr229** [comment]
I do believe open sourcing the whole MS-DOS code in future versions may cause some issues within their copyright but I also believe its better for people to see everything than to throw it on a vault to collect dust.

**Comment by bitcrazed** [comment]
Sorry - no plans to open-source newer versions of MS-DOS at this time.

**Comment by mcadidvijay** [comment]
How to assemble and link source files to get a msdos OS up and running.

**Comment by mcadidvijay** [comment]
Hi everybody, can I make a up and running msdos os using files available in github repository, that is:
SKELIO + SYSINIT + SYSIMES

**Comment by mcadidvijay** [comment]
I'm creating IO.SYS by linking SKELIO + SYSINIT + SYSIMES object files. then I am copying IO. SYS, MSDOS.SYS and COMMAND.COM in a formatted CD. But I didn't get success. Please guide.

**Comment by Lisias** [comment]
@mcadidvijay MS-DOS has no native support for CD-ROMs. You need to use a Floppy Disk, or to build a Yellow-Book CD-IMAGE.

https://searchstorage.techtarget.com/definition/Yellow-Book
https://www.hiren.info/pages/bootablecd
