### ISSUE TITLE
Is license broadly compatible with FreeDOS ? (for code sharing)

### ISSUE THREAD

**Issue by dreamcat4** [Microsoft/MS-DOS#202]
Hi @bitcrazed do you think this is a good idea? Can we develop a better overall DOS boot disk, by using the best pieces of source code from both projects?

My chief question is: It this possible, from a licensing standpoint? Are the 2 sets of licenses even compatible with each other? Or under what specific restrictions?

**Comment by erkinalp** [comment]
FreeDOS is under GPL2. They can take but not give.

**Comment by dl200010** [comment]
FreeDOS is GPL and this is MIT. By those licenses, you could take MS-DOS code and bring it into FreeDOS, but not the other way around. Not legal advice. I would suggest contacting a lawyer before doing something like this.

**Comment by dreamcat4** [comment]
The other part of the question was: But is it a good idea? Well i would say 'no'. At least whilst this open sourcing is limited to versions 1-2 of MS-DOS. Then there is probably very little benefit. Really I have no idea about the specifics here. But would imagine that we would want some much newer version of MS-DOS than this one.
