### ISSUE TITLE
Any plan of Japanese specific MS-DOS source code up to 7.00?

### ISSUE THREAD

**Issue by HikariCalyx** [Microsoft/MS-DOS#21]
Japanese proprietary platforms like NEC PC-9800 series, EPSON PC-x86 series, Fujitsu FM Towns have their own version of MS-DOS.
Unlike IBM compatibles, these Japanese platforms have proprietary system bus, so the existing source code on Github may not likely work on them.

To give you an impression, here's a screenshot of MS-DOS 6.20 for NEC PC-9800 series computer on an emulator.

![nec98_dos620_emulator](https://user-images.githubusercontent.com/29157608/46253646-b46c8100-c4b3-11e8-90ee-34c44e53a919.png)

**Comment by neozeed** [comment]
If you check the international blocks there is hooks for KANJI in the code.  You can find it in a few places, namely getset/dosmes etc.

**Comment by OBattler** [comment]
Yes, but the code needed to specifically boot the OS on the PC-98 or something, is not there, and will probably never be because it's copyright of the respective companies (NEC, Epson, Fujitsu, etc.).

**Comment by HikariCalyx** [comment]
> Yes, but the code needed to specifically boot the OS on the PC-98 or something, is not there, and will probably never be because it's copyright of the respective companies (NEC, Epson, Fujitsu, etc.).

Well, the main purpose is find out the code differences between IBM compatibles and PC-9800 series, this will help for porting or programming since both of them use Intel x86-based processors.

**Comment by Matriks404** [comment]
Could OEM manufacturers theoretically release their MS-DOS 1.x/2.x OEM versions source code? Or is it against Microsoft terms? I think we could contact some of still existent-companies if they have source code for their OEM versions and if they will to release it.

**Comment by bitcrazed** [comment]
The OEM would have to dig up and examine the terms of the license through which they obtained MS-DOS, and the terms/license governing code/modifications they made to the product. Feel free to reach out to them, but I'd set your expectations low.

**Comment by Serentty** [comment]
What about DOS/V for IBM clones? I'm not sure what the licensing situation with that would be, but it wasn't exactly an OEM modification, I think.
