### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by win98se** [Microsoft/MS-DOS#22]
`[LICENSE file](https://githib.com/microsoft/msdos/license.txt)`    
GitHib?

The correct link should be -    
`[LICENSE file](https://github.com/Microsoft/MS-DOS/blob/master/LICENSE.md)`

And maybe you will want to fix the `LICENSE.md` file? It looks really messy.

**Comment by akuckartz** [comment]
Please close, patch was already submitted: https://github.com/Microsoft/MS-DOS/pull/6

**Comment by sundhaug92** [comment]
Fixed by @bitcrazed merging #6, please close

**Comment by bitcrazed** [comment]
Thanks. Fixed.
