### ISSUE TITLE
Issues utilizing memory beyond the first 640 KB

### ISSUE THREAD

**Issue by denislemire** [Microsoft/MS-DOS#25]
Steps to reproduce:

1. Install more than 640 KB into computer system...

That amount of RAM certainly doesn't seem _unconventional_ why won't this work?

**Comment by neozeed** [comment]
The SCP Gazelle doesn't use frame buffered video cards, and reserves no space for peripherials to have any space in the memory map, so it'll allow most of the 1MB as usable address space.

> Microsoft took full advantage of the SCP system capability. In 1988, years after SCP had shut down, they were still using the SCP system for one task only it could perform ("linking the linker"). Their machine was equipped with the full 1 MB of RAM – 16 of the 64 KB cards. That machine could not be retired until 32-bit software tools were developed for Intel's 386 microprocessor.

From here:

http://dosmandrivel.blogspot.com/2007/11/first-dos-machine.html

So as long as you don't need memory mapped peripherials then yeah you can use more than 640kb of RAM.  Even with emm386 you can map up to  753kb of conventional ram (732kb usable) by overwriting the graphical part of the VGA card's frame buffer.

`device=emm386.exe i=a000-afff i=b000-b7ff x=b800-bbef x=c000-c7fff i=c800-cfff i=d000-dfff i=e000-efff noems`

**Comment by bitcrazed** [comment]
Specifically, from http://dosmandrivel.blogspot.com/2007/11/first-dos-machine.html: 

>  IBM, on the other hand, had limited the address space in their PC to 640 KB of RAM due to video and boot/BIOS ROM. This limitation has been called the "DOS 640K barrier", but it had nothing to do with DOS.

**Comment by AnthonyWC** [comment]
"640K ought to be enough for anybody.."

Sorry can't resist. :)

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by bitcrazed** [comment]
@AnthonyWC Actually, [Gates never said that](https://www.computerworld.com/article/2534312/operating-systems/the--640k--quote-won-t-go-away----but-did-gates-really-say-it-.html). No, [really](https://quoteinvestigator.com/2011/09/08/640k-enough/)! :)
