### ISSUE TITLE
Readme in Spanish contains three bugs

### ISSUE THREAD

**Issue by juliojgd** [Microsoft/MS-DOS#253]
Hi,
README.es.d contains the following bugs:

1. tilde (acento gráfico) en siéntete
2. concordancia en "[...] envía una petición (PR` [...]". La primera parte de la frase estaba en segunda persona (tú) ("si deseas enviar") sin embargo la seginda parte estaba en segunda persona (usted) "envíe una petición (PE)" lo cual no concordaba.
3. Error ortográfico: "Este proyecto ha adoptado [...]" Ha es del verbo haber y lleva "h".

I am preparing PR to fix them.

**Comment by RobertLara** [comment]
> Also there should be "más" in:
> "...ser encontrados mas fácilmente" and "Para mas información..."

#304

**Comment by bitcrazed** [comment]
Thanks. Fixed.
