### ISSUE TITLE
Please document which files are belong to which floppy.

### ISSUE THREAD

**Issue by Mr-Pi** [Microsoft/MS-DOS#26]
Something like:

floppy 1:
 * io.sys
 * command.com

floppy 2:
 * format.com

**Comment by HACKER-3000** [comment]
1UP

**Comment by Brayton1234567** [comment]
Yes, I agree.

**Comment by bitcrazed** [comment]
Sorry - no plans. Besides which, OEM's governed how MS-DOS 1.25 & 2.0 were delivered on their hardware, and how files were laid-out on media.
