### ISSUE TITLE
Russian translation of your README

### ISSUE THREAD

**Issue by xCounsel** [Microsoft/MS-DOS#261]
Hi all,

If you are intended to provide your Readme on different languages, please do not forget about translation in Russian. I have prepared this translation, please check it.

----

# Исходный код MS-DOS v1.25 и v2.0
Этот репозиторий содержит исходный код и скомпилированные бинарные файлы MS-DOS v1.25 и MS-DOS v2.0.

Это те же файлы, что были первоначально размещены 25 марта 2014 г. на сайте [Музея компьютерной истории](http://www.computerhistory.org/atchm/microsoft-ms-dos-early-source-code/), они (пере)опубликованы здесь, чтобы их было легче найти, ссылаться на них в текстах и работах, разрешить исследования и эксперименты тем, кто заинтересован в операционных системах для ранних ПК.

# Лицензия
Все файлы в этом репозитории опубликованы под лицензией [MIT (OSI) License](https://en.wikipedia.org/wiki/MIT_License), как это определено в  [файле LICENSE](https://github.com/Microsoft/MS-DOS/blob/master/LICENSE.md), размещенном в корневой папке этого репозитория.

# Делайте контрибьюты!
Исходные файлы в этом репозитории размещены для исторической справки и будут оставаться в том же виде, поэтому пожалуйста, **не отправляйте** пулл-реквесты, предлагая какие-либо изменения в исходные файлы, но не стесняйтесь делать форки этого репозитория и экспериментировать 😊.

Если, все же, вы желаете предоставить дополнительный контент, не относимый к исходному коду, или модификации таких файлов (например, этот README), пожалуйста предоставьте через PR, и мы рассмотрим и примем решение.

Этот проект принял программу [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).  Для получения более подробной информации см. [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) или обратитесь через [opencode@microsoft.com](mailto:opencode@microsoft.com) с любыми дополнительными вопросами или комментариями.

----

Yes, I have read about your order for contributions, and supposed that this issue submitting is a good way to contribute.

**Comment by voyula** [comment]
Open a Pull Request.

**Comment by xCounsel** [comment]
[Have done](https://github.com/Microsoft/MS-DOS/pull/265).
