### ISSUE TITLE
Require wiki about how to build and how to run.

### ISSUE THREAD

**Issue by Anduin2017** [Microsoft/MS-DOS#262]
Require wiki about how to build and how to run.

Or, even how to install.

I have read the source code from some time but still can not get a start point about how to run.

**Comment by HanHeld** [comment]
This is mostly too old to run today.
It might work in an emulator, but probably not.

I believe that the intent of releasing this is to get insight on how they used to do things in the early 80's.

You're intended to learn from this, not to use it on your Ryzen 9 core desktop ;)

**Comment by mcarbonneaux** [comment]
Simply to fork and experiment!
For fun! 
If i can built and execute it on qemu ou vm it's OK!

**Comment by justin-romano** [comment]
Should at least release the old build tools. you will be suprised what some nuts out there will do. Maybe cross compile for Arduino 😂😂😂😂

**Comment by bitcrazed** [comment]
Sorry - the intent of this repo is to preserve a moment in computer history, not to provide a simple way to build and run a very old OS on todays dramatically different hardware.

That's not to say that one could not get this code running, but doing so will take some effort.
