### ISSUE TITLE
^M symbol in TIME.ASM (v2.0)

### ISSUE THREAD

**Issue by Rescor** [Microsoft/MS-DOS#33]
https://github.com/Microsoft/MS-DOS/blob/80ab2fddfdf30f09f0a0a637654cbb3cd5c7baa6/v2.0/source/TIME.ASM#L231

**Comment by Rescor** [comment]
https://github.com/Microsoft/MS-DOS/blob/80ab2fddfdf30f09f0a0a637654cbb3cd5c7baa6/v2.0/source/CHKDSK.ASM#L901
Same.

**Comment by alexsandro-xpt** [comment]
I see that, what is it mean?!

**Comment by wrljet** [comment]
Ctrl+M is ASCII carriage return.  It sometimes displays like that when a file is in MS-DOS format and has a bare CR with no LF following.

Bill

**Comment by bitcrazed** [comment]
We'd like to avoid making changes to source file contents to protect as much byte-accurate historical content as possible.
