### ISSUE TITLE
DOS subsystem for Win10? I want my 90s childhood back!

### ISSUE THREAD

**Issue by shinjox27** [microsoft/MS-DOS#395]
@bitcrazed I understand MS has NO future plans to release anymore DOS code and I'm respectful of that however seeing as North Korea's RedStar OS 3.0 comes bundled with Win3.1 in total violation of the EULA Can't us paying Windows 10 customers such as myself get something similar to run our favorite old school DOS applications on? Allowing applications to install in a subsystem that will launch without changing directories could even attract some Linux users. who use DOSbox I would love to launch Wordstar in a powershell while exploring the Organ Trail on Monkey Island! So if possible keep the code and bring us a blast from the MS past!

**Comment by dodona2** [comment]
run dosbox under linux, and you get your 90s childhood back

**Comment by woachk** [comment]
The DOS subsystem is currently there still together with Win16 for 32-bit Windows 10. SoftPC used to exist for Win16/DOS on other architectures with NTVDM, but only virtual 8086 mode is used these days.

If you really want to try: https://github.com/leecher1337/ntvdmx64

**Comment by domoaligato** [comment]
> My data was collected as much as if I was using windows thanks to Amazon
Microsoft is tracking way more than Ubuntu is sending to Amazon.
This script can help.
https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/block-telemetry.ps1

**Comment by shinjox27** [comment]
> This script can help.
> https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/block-telemetry.ps1

LMFAO oh HELL NO! 
#"wdcp.microsoft.com"                       # may cause issues with Windows Defender Cloud-based protection
    #"dns.msftncsi.com"                         # This causes Windows to think it doesn't have internet
#"storeedgefd.dsx.mp.microsoft.com"         # breaks Windows Store
#"sls.update.microsoft.com"                 # may cause issues with Windows Updates
 # can cause issues with Skype (#79) or other services (#171)
 # "login.live.com"                  # prevents login to outlook and other live apps
# Please note that adding these domains may break certain software like iTunes
# or Skype. As this issue is location dependent for some domains, they are not
# commented by default

Sounds like the source code to windows Vista to me

**Comment by JL2210** [comment]
@shinjox27 

> I used Linux for over 10 years.
> Back in my day around the time you could only find PC's running Windows Vista people like me switched because unless you were throwing Apple Prices towards your PC it probally came with 250MB to 500MB of RAM which caused a Blue Screen of death every 20 Minutes and Windows XP service pack 3 put a TCP patch in place which made gaming lag horribly even on DSL which made downgrading not a appealing option.
> 
> In over 10 years
> 
> Ubuntu alone has seen more desktop changes then every version of Windows Combined.
> 
> I was forced onto external audio for years due to pulse audio issues.
> 
> Their we're no app stores all application Mangement was done in the terminal
> 
> Everything I worked on outside of the system had to be saved to external sources because updating the system possibly ment loosing everything due to a glitch
> 
> My data was collected as much as if I was using windows thanks to Amazon
> 
> For a few years all my media had to be converted to free formats.
> 
> I have never been able to use Netflix
> 
> I had to teach myself Vim key bindings, BASH, Apt, Repo Mangement, Init systems and systemd, ZSH, SSH, VNC, the Linux filesystem to see where apps where storing data all with 0 experience while going through these issues and so many more took a while to get comfy

Most of these would be fixed by just switching to Debian (enable non-free software and you'll get all of them except the next noted).

For this
> I had to teach myself Vim key bindings, BASH, Apt, Repo Mangement, Init systems and systemd, ZSH, SSH, VNC, the Linux filesystem to see where apps where storing data all with 0 experience while going through these issues and so many more took a while to get comfy

I don't mind any of these. They are second-nature to me, and they can be extremely useful if you know them. If you'd like, I could help.

**Comment by xavery** [comment]
> For a few years all my media had to be converted to free formats.
THE HORROR!!!!!!!!!!!!!!1111111111111111

**Comment by justingoldberg** [comment]
PCEM provides a fairly accurate DOS emulation system. One caveat: you are required to download a real BIOS image.

**Comment by bitcrazed** [comment]
Appreciate your ask, but other than the NTVDM that we continue to ship in 32-bit editions of Windows - all the way 10 up through current (and am sure many future) releases - we have no plans to release ancient OS products, sorry.
