### ISSUE TITLE
Please consider porting Teams to this system, it may be more reliable

### ISSUE THREAD

**Issue by davidcantrelluk2** [microsoft/MS-DOS#398]

**Comment by TheFerrango** [comment]
Could Teams fit inside the conventional memory limit?

**Comment by davidcantrelluk2** [comment]
Easily, and with room left over for an IP stack. It's just IRC with a thick layer of Ugly smeared on top.

**Comment by sylvandb** [comment]
could use KA9Q NOS for the stack.

**Comment by davidcantrelluk2** [comment]
KA9Q is fat and bloated, something like 150K in its DOS version. I'd go with a port of one of the other Z80 IP stacks, which are about a tenth of the size and so small enough to make use of DEBUG.COM almost tolerable to build it.

**Comment by bitcrazed** [comment]
Sorry, no ;)
