### ISSUE TITLE
When will WRK become free software?

### ISSUE THREAD

**Issue by njlyf2011** [microsoft/MS-DOS#402]
When will WRK become free software?

**Comment by dodona2** [comment]
what the heck is a WRK?

**Comment by njlyf2011** [comment]
Windows Reserach Kernel

**Comment by dodona2** [comment]
program your own Windows Reserach(sic!) Kernel, and we'll see if you give it away for free.

**Comment by j123123** [comment]
Try ReactOS

**Comment by domoaligato** [comment]
https://github.com/markjandrews/wrk-v1.2 ?

**Comment by bitcrazed** [comment]
No idea.
