### ISSUE TITLE
Branch for producing working copy of working MS-DOS?

### ISSUE THREAD

**Issue by JL2210** [microsoft/MS-DOS#414]
I propose to keep the old MS-DOS (untampered) in a separate branch, similar to what [winfile](https://github.com/Microsoft/winfile) does. This would keep the original code unchanged (although I do suggest some edits to fix files that were cut in half) and allow work to continue the development of MS-DOS, potentially allowing to build a working copy.

**Comment by bitcrazed** [comment]
As per the readme:

> The source files in this repo are for historical reference and will be kept static, so please don’t send Pull Requests suggesting any modifications to the source files, but feel free to fork this repo and experiment

So, feel free to experiment, but we have no plans to maintain or create working versions of MS-DOS from this source.
