### ISSUE TITLE
How to install MS-DOS on my personal computer without any floppy disk drivers or CD-ROM drivers

### ISSUE THREAD

**Issue by EdwinIZ8** [microsoft/MS-DOS#416]
I want to install MS-DOS on my personal computer for studying and working.  
I have no CD-ROM driver or  floppy disk driver, But I have a USB flash disk.  
I saw the bin directory and the source directory, but how to use them to install MS-DOS on my pc? Should I copy these directories to my USB flash disk directly and boot from my usb driver?  
Thanks!

**Comment by ibuprophen1** [comment]
According to the following Microsoft TechNet Forum link... 

https://social.technet.microsoft.com/Forums/windows/en-US/e4696428-6999-4946-81c1-ea934eb6fd41/dos-622 

... The Microsoft Staff provided the following link to obtain ISO images, that actually has, a good handful of ISO images of various MS-DOS and other older Microsoft Products. 

https://www.allbootdisks.com/download/iso.html 

Enjoy! :-) 


~Ibuprophen

**Comment by EdwinIZ8** [comment]
> According to the following Microsoft TechNet Forum link...
> https://social.technet.microsoft.com/Forums/windows/en-US/e4696428-6999-4946-81c1-ea934eb6fd41/dos-622
> ... The Microsoft Staff provided the following link to obtain ISO images, that actually has, a good handful of ISO images of various MS-DOS and other older Microsoft Products.
> https://www.allbootdisks.com/download/iso.html
> Enjoy! :-)
> ~Ibuprophen

Thanks for you replying.  
  
I saw the links you mentioned above. In the second link, it has many dos versions ranging from 3.3 to 6.22. And on GitHub, Microsoft/MS-DOS provides 1.25 and 2.0. I want to use MS-DOS for studying and working, which version should I choose?  
  
Best wishes!    
  
EdwinIZ8

**Comment by ibuprophen1** [comment]
"MS-DOS" versions ranged from v1.25 - v8.0 and your question is really challenging to answer because it all depends upon what it is your looking to study (and so on). 

If you take a look at the following example link, you may be able to understand the basic comparisons of the "DOS" versions. 

https://en.m.wikipedia.org/wiki/Comparison_of_DOS_operating_systems 


~Ibuprophen

**Comment by NanhuGITHUB** [comment]
Also you can use a Virtual Machine.

**Comment by bitcrazed** [comment]
If your goal is to experiment with MS-DOS, I would encourage you to use a virtualization platform to host Virtual Machines, rather than trying to boot actual hardware. If you are determined to do the latter, I'd recommend buying some vintage hardware and disks, and a USB floppy drive from ebay etc.
