### ISSUE TITLE
compile on linux

### ISSUE THREAD

**Issue by asklinux** [microsoft/MS-DOS#418]
how can i compile this code in linux ? any example ? thanks

**Comment by gungwald** [comment]
You could try NASM or MASM inside Dosbox. Just some ideas. Not sure if they'll work.

    On Monday, May 6, 2019, 11:00:27 PM EDT, hasnan <notifications@github.com> wrote:  
 
 
how can i compile this code in linux ? any example ? thanks

**Comment by bitcrazed** [comment]
No idea. I can't even compile this into a fully running OS on Windows, but as stated in the readme, that's not the point of this historical archive.
