### ISSUE TITLE
[feature request] Opensource QBasic maybe?

### ISSUE THREAD

**Issue by shi-yan** [microsoft/MS-DOS#423]
QBasic is my sweet childhood memory. I'd like to see it having a new life, perhaps with WebAssembly.

Not sure if this type of request should be submitted here. My apologies if it shouldn't.

**Comment by ibuprophen1** [comment]
I don't believe that this Repo is the right one and that name was a REAL blast from the past LOL! 

I performed a quick search and the following Repo looks like it may be the right one, but it doesn't seem to be very active. 

https://github.com/texttheater/QBASIC

I think there's a few developers somewhere on Github that has been maintaining the QBasic under the same or different name. 

I'm not 100% sure where, but maybe someone here can provide you with a little guidance on where you can go. 

I do wish you the best of luck! :-) 


~Ibuprophen

**Comment by denzuko** [comment]
Quickbasic still lives on: 

https://github.com/Galleondragon/qb64

There's even support for modern hardware, 64 bit processors, networking, and more.

**Comment by gungwald** [comment]
There is also https://www.freebasic.net/
It has a QuickBASIC mode. But QuickBASIC is actually an extended qbasic.

Sent from Yahoo Mail on Android 
 
  On Fri, Oct 11, 2019 at 1:03 AM, Dwight Spencer<notifications@github.com> wrote:   
Quickbasic still lives on:

https://github.com/Galleondragon/qb64

There's even support for modern hardware, 64 bit processors, networking, and more.

**Comment by bitcrazed** [comment]
As others have kindly pointed out, there are many modern, thriving BASIC alternatives which I think you'll have much more productive fun and enjoyment from ;)
