### ISSUE TITLE
Where is source code of 3.30 and 5.0 versions?

### ISSUE THREAD

**Issue by crcaicedo** [microsoft/MS-DOS#424]
What a nice and interesting share this repo from MS. But I wonder if they plan to share the sources of 3.3 and 5.0 versions of MS-DOS, the most used versions of the most used OS of computing history

**Comment by bitcrazed** [comment]
No idea. I checked down the back of the sofa and under the coffee machine, but couldn't find them anywhere ;)

Realistically, I am sure they exist, but they also likely contain 3rd party licensed code for which we do not have rights of distribution.

Sorry!
