### ISSUE TITLE
getting it working

### ISSUE THREAD

**Issue by T8z5h3** [Microsoft/MS-DOS#49]
hi,
could we get this to a point where we could do a full install on to a machine?

**Comment by KR0SIV** [comment]
I don't see how this constitutes an 'issue' 
of course you can, you need to compile it with a proper assembler.

**Comment by bitcrazed** [comment]
@T8z5h3 Unknown. We've not attempted to build MS-DOS from these sources; we're just sharing the resources here as a historical reference.

**Comment by lenucksi** [comment]
I actually have tried to assemble working parts from these sources. The results were rather mixed, I did however manage to boot the results on a recent VirtualBox machine with some external additives if I remember correctly.
