### ISSUE TITLE
Separate 1.25 and 2.xx into separate branches

### ISSUE THREAD

**Issue by sundhaug92** [Microsoft/MS-DOS#5]
This'd make the repo cleaner but would make it more difficult to fix issues in common files (like licensing)

**Comment by blanham** [comment]
And why not add DOS 3, 4, 5, 6, and 7? ;)

**Comment by piranna** [comment]
I agree with that, specially if 2.xx branch from the 1.25 one to keep a sorted changes history.

**Comment by AntonioND** [comment]
There is no need to have two branches. You could argue that the same branch could have one commit with version 1.25 and the next one with 2.xx (but without the intermediate changes it's quite useless), but there is certainly no reason to keep them in different branches.

Also, different branches would mean that someone that sees the repository wouldn't see all the content right away. Branches obscure the files in a repository and should only be used for development. This is a repository used for reference, so just using the master branch is fine.

**Comment by sundhaug92** [comment]
@blanham From a [tweet](https://twitter.com/richturn_ms/status/1045783501977473024), it seems like it's up to interest, guessing DOS 1.25 and 2.xx came first due to prior release via CHM.
@AntonioND Those are good points, I did not consider that.
