### ISSUE TITLE
Why don’t you archive this repo?

### ISSUE THREAD

**Issue by pmkary** [microsoft/MS-DOS#53]
Since it’s a historic piece why don’t you archive it so that you don’t have to write about contributions and anwser issues and PRs?

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by gusbemacbe** [comment]
Archiving this repository also can help to prevent the trolls.

**Comment by bitcrazed** [comment]
I was waiting to see if anyone had anything constructive to add. It appears not and will archive v. soon.

**Comment by kickstart530** [comment]
Keep it someone will learn and try to improve it someday

**Comment by borrougagnou** [comment]
At when MS-DOS 6 ?

**Comment by bencz** [comment]
@borrougagnou I'm waiting to see the MS-DOS 6.0 source code as well!

**Comment by bitcrazed** [comment]
Sorry @borrougagnou and @bencz - no plans. 

And please don't hijack unrelated issues - create new ones if you have a genuine issue/ask.

**Comment by domoaligato** [comment]
if your not going to archive it then please address the "issues" like the guy posting about a dos subsystem for windows. the troll is strong in that one. same with the spaces inside dos lol.

**Comment by ibuprophen1** [comment]
Only the Source Code for the MSDOS v1.25 & v2.0 is available here... 

https://archive.org/details/MSDOSsrc 

Just an FYI... :-) 


~Ibuprophen

**Comment by buricco** [comment]
The more interesting version to me is 3.3, 4.0 or 5.0 (stripped of mirror, unformat and undelete naturally); but all of these would require permission, I suppose, from IBM as well as MS's own legal department to release.

**Comment by bitcrazed** [comment]
Sorry - am going to archive this repo - there's not much more to be said to be honest. I think we should just leave this wonderful historical artifact here for all to enjoy and ponder.
