### ISSUE TITLE
Will it run DOOM?

### ISSUE THREAD

**Issue by hex86** [Microsoft/MS-DOS#7]

**Comment by Hamzantal** [comment]
of course. no question

**Comment by MrQueeba** [comment]
Anything with a screen can run DOOM, so of course this can run DOOM.

**Comment by RandomGuyDTB** [comment]
Okay but can it run Crysis?

**Comment by armornick** [comment]
Actually, the serious answer is no. DOOM requires a mimum version of DOS 4.0 and this is DOS 2.0.

**Comment by Krutonium** [comment]
I wonder how hard it would be to add what is required, though.

**Comment by metacritical** [comment]
This source is 20 yrs too late people have already developed free DOS.

**Comment by lloydjatkinson** [comment]
@metacritical You've clearly missed the point of this repo.

**Comment by b4284** [comment]
Great. But makes wonders of why DOOM 1 needs DOS 4.0 to run. Does anyone know why?

**Comment by bitcrazed** [comment]
@b4284.Two things:Himem.sys and/or EMM386.sys.

**Comment by metacritical** [comment]
> @metacritical You've clearly missed the point of this repo.
> @lloydjatkinson 
What is the point if you cant compile it?

**Comment by neozeed** [comment]
> > Great. But makes wonders of why DOOM 1 needs DOS 4.0 to run. Does anyone know why?
> > the multi-tasking features.

I've wondered myself.  I can't see it being the IFS stuff in the later versions of dos, although I do suspect things like share & file locking could be an issue.  I'm still trying to work out what is all missing from this though.

**Comment by neozeed** [comment]
> @b4284.Two things:Himem.sys and/or EMM386.sys.

neither of these are needed to enter protected mode directly from MS-DOS.

**Comment by CecilHarvey** [comment]
> @b4284.Two things:Himem.sys and/or EMM386.sys.

It is "EMM386.EXE" rather than "EMM386.sys" :)

**Comment by genewitch** [comment]
> 
> 
> > @metacritical You've clearly missed the point of this repo.
> > @lloydjatkinson
> > What is the point if you cant compile it?

You can compile it, though, using this 8086 VM: http://ioccc.org/2013/cable3/ see the "hint.txt / hint.html" files for an explanation. That VM can be compiled with TCC https://bellard.org/tcc/

**Comment by anonymone** [comment]
No,It will alive as another type of meaning.

**Comment by metacritical** [comment]
> > > @metacritical You've clearly missed the point of this repo.
> > > @lloydjatkinson
> > > What is the point if you cant compile it?
> 
> You can compile it, though, using this 8086 VM: http://ioccc.org/2013/cable3/ see the "hint.txt / hint.html" files for an explanation. That VM can be compiled with TCC https://bellard.org/tcc/

@genewitch  This ioccc entry is amazing! Didnt know someone did an entire 8086 VM in 3K or C.

**Comment by pgodwin** [comment]
@metacritical you might be interested in https://github.com/adriancable/8086tiny which is basically the unobfuscated version of the ioccc entry.

**Comment by iajrz** [comment]
> > @metacritical You've clearly missed the point of this repo.
> > @lloydjatkinson
> > What is the point if you cant compile it?

Hi - I'm coming into this convo with best intentions, no snark - and assuming similarly best intentions. Please take this comment at face value.

There's something particularly interesting in having an OS that has so little code; makes you think about what's actually the least you need to get things rolling, and you could in theory understand and hold all the project in your head at the same time.

For people studying OS development, it's great; I think I even have a copy of the old Operating Systems handbook, which did an analysis of MS-DOS (among other OSes) - this code will put everything into perspective when I inevitably go back to re-read it. If you want to get into low-level programming this is fun, too. Many embedded systems have more resources than the computers for which DOS 1 was built, so -- it's a historically relevant point starting point to understanding and building your own stuff.

**Comment by DavidBerdik** [comment]
Yes

**Comment by bitcrazed** [comment]
Alas, no. Doom requires more than 640KB to run ;)
