### ISSUE TITLE
How to compile MS-DOS?

### ISSUE THREAD

**Issue by dzejqub** [Microsoft/MS-DOS#74]
Hello, i'm tried compile this code on NASM on Ubuntu 18.04, and i'm can't because output give me error (in terminal). I'm so sorry for not knowing, because I am just a beginner, young programmer.

**Comment by edwtie** [comment]
Use old versions of NASM. it works only at older computers.. not at newer computers

**Comment by tommai78101** [comment]
See https://github.com/Microsoft/MS-DOS/issues/8

This issue is a duplicate.

**Comment by bitcrazed** [comment]
Already answered. Please review closed issues before posting new ones.
